### ISSUE TITLE
Assets Directory for Illustrations and Photos

### ISSUE THREAD

**Issue by carl5004** [mn-pollinators/assets#15]
Once we are able to add illustrations and photos (or before that), we will want to organize the directory for those assets. 
I suggest something similar to the way they are currently organized in the ENRTF Google Drive (these are as **folders**):

- Assets
   - JSON files 
   - Illustrations 
      - Plants
      - Pollinators
      - Nests
      - Backgrounds
      - Other
   - Images [Should_ we call this "Photographs" instead?]
      - Pollinators
      - Flowers
      - Nests
      - Other

What do you think @floogulinc?

(Apologies if this is not the way this is typically described, and/or if I am using improper syntax.)

**Comment by floogulinc** [comment]
I think that's pretty much right, here is what I think it would look like more exactly:

```
assets/ (the root of the repo)
├── art/
│   ├── LICENSE
│   ├── plants/
│   ├── pollinators/
│   ├── nests/
│   └── other/
├── photos/
│   ├── pollinators/
│   ├── flowers/
│   ├── nests/
│   └── other/
├── bees.json
├── bees.schema.json
├── flowers.json
├── flowers.schema.json
├── nests.json
├── nests.schema.json
├── README.md
├── LICENSE
```

I changed `illustrations` to `art` because it seems simplier and eaiser to type and such. Also `images` to `photos`, photos seems more descriptive of what they are.

One thing I noticed is that we call the JSON "flowers" and "bees" and that is also the terminology used in our existing code in the game, rather than "pollinators" and "plants." It seems like they should be consistent. I think there are two potential solutions. Either:

1. Change the directories for photos and art to "flowers" and "bees" and make sure that other pollinators that aren't bees/aren't in the bees json and plants that aren't flowers/aren't listed in the flowers json (like extra grass and such) are in the "other" directory.
2. Change the JSON to "pollinators" and "plants" and include info about the non-bee pollinators and non-flower plants in them.

I kinda lean towards the first but I would like to hear what you think.

**Comment by carl5004** [comment]
The first option sounds good. So it would be:
```
assets/ (the root of the repo)
├── art/
│   ├── LICENSE
│   ├── flowers/
│   ├── bees/
│   ├── nests/
│   └── other/
├── photos/
│   ├── bees/
│   ├── flowers/
│   ├── nests/
│   └── other/
├── bees.json
├── bees.schema.json
├── flowers.json
├── flowers.schema.json
├── nests.json
├── nests.schema.json
├── README.md
├── LICENSE
```
What about the backgrounds? Should we put them in a separate folder or just in `other`?

**Comment by floogulinc** [comment]
I think there will only be a few background art images it would be fine to put them in "other"
